### ISSUE TITLE
dash: pipes are not working - RuntimeError: unreachable

### ISSUE THREAD

**Issue by milahu** [sagemathinc/cowasm#46]
this will crash the shell at https://cowasm.sh/

```sh
seq 1 10 | head -n 1
```

js console

```
658.bundle.js:2 /usr/bin/sh RuntimeError: unreachable
    at growjobtab (wasm://wasm/00521052)
    at makejob (wasm://wasm/00521052)
    at evalpipe (wasm://wasm/00521052)
    at evaltree (wasm://wasm/00521052)
    at cmdloop (wasm://wasm/00521052)
    at main (wasm://wasm/00521052)
    at e.default.run (658.bundle.js:2:52854)
    at Object.cowasm_vforkexec (658.bundle.js:2:4329)
    at n.<computed> (658.bundle.js:2:6410)
    at /aa318ea0a6040fd50963.wasm
```

**Comment by williamstein** [comment]
Thanks for adding this to the todo list and trying out the cowasm shell.   I have indeed not implemented dash pipes yet at all.  It requires running a subprocess (all in the same WebAssembly VM) and capturing the output, which is something that probably isn't too hard to figure out and will be exciting.  But it's not done.

Any other thoughts about cowasm?

**Comment by martin12333** [comment]
> Any other thoughts about cowasm?

I have several thoughts. My first thought:

one of my dream projects is something like: fragments of Ubuntu compiled to wasm

But I will have to learn a lot.

I am glad, that I was able to install cowasm dash and utils locally.
(my experiments are at
https://github.com/martin12333/marti-onedrive/blob/main2/cowasm/cowasm.f8.sh
)

**Comment by williamstein** [comment]
> fragments of Ubuntu compiled to wasm

Yes, that's basically one way to think of cowasm, except with Ubuntu maybe replaced by FreeBSD.  The FreeBSD utilities are mostly much smaller and easier to hack on that corresponding GNU tools, so I was able to build a ton of them for WASM this way, and you can see them all in the shell.

Anyway, welcome to the project!

**Comment by milahu** [comment]
> It requires running a subprocess (all in the same WebAssembly VM) and capturing the output, which is something that probably isn't too hard to figure out and will be exciting.

note that pipes are "incremental", so in theory, they can work on infinite data streams

examples ...

`seq 1 100000000 | head -n 1` should write `1\n` from seq to head
and head should stop seq after the first line

`cat /dev/random | head -c 1 | xxd -p` should read only 1 byte from /dev/random

`cat data.txt | sort --random-sort | head -n 1`
should read only some lines of data.txt

there is also a difference between line-buffered and unbuffered ...
line-buffered is useful when working with line-based text files

devil in the details ; )

**Comment by williamstein** [comment]
> note that pipes are "incremental", so in theory, they can work on infinite data streams

I realize that.  Unfortunately it's impossible to support that using the model I'm implementing for this with the current Wasm spec (of one single wasm instance and general wasm code).  There's just no way to support multiple processes running at once in general.  I might also implement a second much more complicated and less efficient subprocess execution model someday that supports that.

**Comment by williamstein** [comment]
There are a lot of tradeoffs with speed versus functionality. One extreme for situations where speed is not important, there is https://copy.sh/v86/?profile=archlinux, which is a full Linux install running under WASM via an x86 emulator.  But it's an order of magnitude (or more) slower at everything, which is not acceptable for me.

**Comment by milahu** [comment]
> speed versus functionality

both ; )

> I might also implement a second much more complicated and less efficient subprocess execution model someday that supports that.

a process scheduler ...

sounds like i should continue https://github.com/milahu/shelljs-async
where pipes are "yield buffered" https://github.com/milahu/shelljs-async/blob/main/src/lib/pipe.js
i just need to rewrite everything as async generators ...
see also https://github.com/miketalbot/js-coroutines

**Comment by williamstein** [comment]
> a process scheduler...

There was something that did this before WebAssembly -- https://browsix.org/  -- but it was like 100x slower at least, so obviously nobody used it.  Of course with WASM and SharedArrayBuffers/Atomics, it is possible to do something that is fast.  That said, sharing state, e.g, of the filesystem, environment, etc., becomes much more complicated and slower.  Right now, memfs lives only in memory in one single WebWorker, whereas a multi-process approach like Browsix had requires having multiple WebWorkers, and the filesystem becomes much more complicated to share between them.  But it's possible.

**Comment by williamstein** [comment]
Thanks for the links!

**Comment by williamstein** [comment]
Neat - I didn't know they actually ported dash and were using that in wasmer.sh too.  I wonder if they are solving all the same problems on my todo list already or what approach they have taken...  E.g., dash uses setjmp/longjmp, so I've been rewriting it to not do that.

**Comment by williamstein** [comment]
I suspect it is dash mainly because of 

<img width="215" alt="image" src="https://user-images.githubusercontent.com/1276278/207145479-676ce928-74be-4b1a-bd7d-faea7897892b.png">

**Comment by martin12333** [comment]
> Neat - I didn't know they actually ported dash and were using that in wasmer.sh ***too***

(if I understand correctly, dash is ***only*** in the  wasmer.sh (the recent website) ) 

( in the webassembly.sh (the old website), there is probably a js-written, old, mini-shell )

**Comment by williamstein** [comment]
now fixed

**Comment by milahu** [comment]
https://github.com/sagemathinc/cowasm/commit/57b662677503bd1f84c10935d70ba2e3962bd494

https://github.com/sagemathinc/cowasm/blob/57b662677503bd1f84c10935d70ba2e3962bd494/core/dash/src/patches/07-pipeline-without-fork.patch#L27-L42

at [cowasm.sh](https://cowasm.sh/) this fails with

```
(cowasm)$ seq 1 10 | head -n 1
sh: 1: Pipe output open failed
sh: 2: Pipe input open failed
```

js console
`dup2(infd, 0);` throws `Error: invalid file descriptor` because `(infd < 0)`
`dup2(outfd, 1);` throws `Error: invalid file descriptor` because `(outfd < 0)`

```
WARNING: Posix library call to dup2 raised exception without error code.  The raised error is 'Error: invalid file descriptor'
(anonymous) @ index.js:139
$evalpipe @ 005313fa:0x16325
$evaltree @ 005313fa:0xf782
$cmdloop @ 005313fa:0x6865e
$main @ 005313fa:0x68201
run @ posix-context.js:164
```

**Comment by williamstein** [comment]
Thanks for testing. It was only fixed locally under node.  Now it's implemented for the web too at https://cowasm.sh via a different approach.

<img width="1610" height="922" alt="Image" src="https://github.com/user-attachments/assets/375a486d-b8ae-4cf7-8b52-11ff2e9061d6" />

Also using "viz" to edit files is somewhat supported (not rock solid yet -- somehow it gets stuck sometimes, but I don't know exactly how to reproduce it).

**Comment by milahu** [comment]
yay : )
19c116bd59c70887dd849a9e6fd0d919d9e6921e

nitpick:
`dup2(infd, 0);` still fails if `(infd < 0)`

[07-pipeline-without-fork.patch](https://github.com/sagemathinc/cowasm/blob/19c116bd59c70887dd849a9e6fd0d919d9e6921e/core/dash/src/patches/07-pipeline-without-fork.patch#L32)

```c
			if (prevpath) {
				infd = open(prevpath, O_RDONLY);
				if (infd < 0)
					sh_error("Pipe input open failed: %s", strerror(errno));
				save0 = savefd(0, 0);
				dup2(infd, 0);
				close(infd);
			}
```

stress test: 500 cats

desktop: 0.15 seconds
browser: 4 seconds = 24x slower

```sh
echo x|
cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|
cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|
cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|
cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|
cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|
cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|
cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|
cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|
cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|
cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|
cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|
cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|
cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|
cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|
cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|
cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|
cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|
cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|
cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|
cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|
cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|
cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|
cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|
cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|
cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|cat|
cat
```
