### ISSUE TITLE
npx dash-wasm: after any cat command, subsequent commands have problems with stdout

### ISSUE THREAD

**Issue by martin12333** [sagemathinc/cowasm#49]
# dash-wasm installed by npm

```sh


cd ~/10-cowasm/node_modules/dash-wasm

vscode ➜ ~/10-cowasm/node_modules/dash-wasm $ npx dash-wasm -x

(cowasm)$ cat wrongname1
+ cat wrongname1
cat: wrongname1: No such file or directory

(cowasm)$ cat wrongname1
+ cat wrongname1
cat: wrongname1: No such file or directory
cat: stdout: Bad file descriptor


(cowasm)$ cat /cowasm/usr/share/termcap
+ cat /cowasm/usr/share/termcap
cat: stdout: Bad file descriptor


(cowasm)$ echo abc
+ echo abc
sh: 4: echo: echo: I/O error


(cowasm)$ python
+ python
Python 3.11.0 (main, Nov 29 2022, 20:26:05) [Clang 15.0.3 (git@github.com:ziglang/zig-bootstrap.git 0ce789d0f7a4d89fdc4d9571 on wasi
Type "help", "copyright", "credits" or "license" for more information.

# i cannot see what i am typing
# 78*89
# aaaaaaaaa
# quit()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 8] Bad file descriptor

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'aaaaaaaaa' is not defined

Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
OSError: [Errno 8] Bad file descriptor


(cowasm)$

```

# (in browser, commands work correctly)
(but with 1 extra error message)

```sh

(cowasm)$ cat wrongname1
cat: wrongname1: No such file or directory

(cowasm)$ cat wrongname1
cat: wrongname1: No such file or directory

cat: stdout: Bad file descriptor

(cowasm)$ echo skfjdsf
skfjdsf

(cowasm)$ echo $PATH
/usr/bin:.

(cowasm)$ python
Python 3.11.0 (main, Nov 29 2022, 20:26:05) [Clang 15.0.3 (git@github.com:ziglang/zig-bootstrap.git 0ce789d0f7a4d89fdc4d9571 on wasi
Type "help", "copyright", "credits" or "license" for more information.

>>> fhgfh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'fhgfh' is not defined


```

# (in a rebuilt dash, no errors)

But I have built only dash and tar (contains cpio and cat).

```sh

cd ~/cowasm/
./bin/dash-wasm-raw  -ex

# note: but /cowasm does not exist

cd packages
cd tar
cd dist
cd wasm
cd bin
ls -l

./cat wrongname1
...

```

**Comment by martin12333** [comment]
# (in browser, commands work correctly)
(but with 1 extra error message)

EDIT I have cut this chapter into a comment


```sh

(cowasm)$ cat wrongname1
cat: wrongname1: No such file or directory

(cowasm)$ cat wrongname1
cat: wrongname1: No such file or directory

cat: stdout: Bad file descriptor

(cowasm)$ echo skfjdsf
skfjdsf

(cowasm)$ echo $PATH
/usr/bin:.

(cowasm)$ python
Python 3.11.0 (main, Nov 29 2022, 20:26:05) [Clang 15.0.3 (git@github.com:ziglang/zig-bootstrap.git 0ce789d0f7a4d89fdc4d9571 on wasi
Type "help", "copyright", "credits" or "license" for more information.

>>> fhgfh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'fhgfh' is not defined


```

**Comment by martin12333** [comment]
# (in a built dash, no errors)

EDIT I have cut this chapter into a comment



EDIT
But I don't mean that there were something wrong with the npm version. ...  I am still not sure how  I  should *run* a built dash  correctly. I am still studying. And I have built only dash and tar (contains cpio and cat). 

```sh

...
git clone ...
cd ...
make
...
cd ~/cowasm/
./bin/dash-wasm-raw  -ex
# maybe a better invocation is something like
npx kernel dash

# note: but /cowasm does not exist

cd packages
cd tar
cd dist
cd wasm
cd bin
ls -l

./cat wrongname1
...

```

**Comment by williamstein** [comment]
The problem might just be that I haven't finished implementing all error handling paths in dash.

The original dash uses setjmp/longjmp for error handling.  However, those don't exist in WASM (except via the not-pretty asyncify), so I'm basically rewriting dash to not use them by instead passing back error codes.  I did this in some cases, but not everywhere yet.    Fortunately, the source code of dash is relatively easy to understand :-).   If you know C, and want to help with this, I can give you some pointers.

(Cowasm is BSD licensed, so your contributions are to a fully open source project.   I'm having to take a break for a bit from very active cowasm development to catch up on a bunch of other things.)

**Comment by martin12333** [comment]
Ok, I will just now add the remaining 2 mentioned experiments ... for completeness, and then I will read your comment again.

**Comment by martin12333** [comment]
# LATER: bin/cat from fs.zip ... errors even  when I bypassed dash-wasm ...  when I ran it from  npx **kernel dash**

todo comment

**Comment by martin12333** [comment]
# LATER: the built ./cat from the tar package ... works ok  even  when I ran it from **npx  dash-wasm**


todo comment

**Comment by martin12333** [comment]
(I have stopped suspecting unionfs, and started to suspect something in coreutils/cat, something that is not used in tar/cat )

**Comment by martin12333** [comment]
## stdout is closed

I suspected, that after the end of the `cat`, the parent shell's stdout is in the closed state.

Experiment:

```sh-session

cd ~/10-cowasm/node_modules/dash-wasm
npx dash-wasm   -x

python

import os, sys
os.fstat(1)
quit()

```

os.stat_result(st_mode=8640, **st_ino=3, st_dev=98**, st_nlink=1, st_uid=0, st_gid=0, st_size=0, st_atime=1673941490, st_mtime=1673941488, st_ctime=1673880218)

```sh-session

cat anyname1
cat anyname1
echo abc

python

import os, sys
x=os.fstat(1)
print(x, file=sys.stderr)

```


os.stat_result(st_mode=8640, **st_ino=0, st_dev=0**, st_nlink=1, st_uid=0, st_gid=0, st_size=0, st_atime=1673941624, st_mtime=1673941624, st_ctime=1673941624)




Hypothesis: there is only one stdout for cat.wasm, dash.wasm, python.wasm ?


I plan to learn how to use the DEBUG ... https://www.npmjs.com/package/debug
